# Build, run unit tests
name: CMake build and run unit test matrix

on:
  push:
    branches:
      - main
      - develop
env:
  BUILD_TYPE: Release
jobs:
  build_matrix:
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
#    defaults:
#      run:
#        shell: bash
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: main
      - name: create-build-dir
        run: cmake -E make_directory ${{github.workspace}}/build
      - name: configure-cmake
        run: cmake ${{github.workspace}}/build examples/intro_generic_programming
      - name: build
        run: cd build && cmake --build .
      - name: run-unit-test
        run: cd build && ctest
